config/routes.rb
Rails.application.routes.draw do
  namespace(:admin){ resources :internal_images }
  namespace(:admin){ 
    resources :configuration_sites
    resources(:products) do
      resources :product_images
    end
    resources :fiber_types
    resources :roll_widths
    resources :height_fibreas
    resources :product_lines
    resources(:featureds) do
      member do 
        get :destroy_image
      end
    end 
    resources :newsletters
    resources :users
    root :to => 'products#index'
  }
  post '/tinymce_assets' => 'tinymce_assets#create'   
  post '/tinymce_documents' => 'tinymce_documents#create' 
  localized do
    resources :products, :only => [:show]
    resources :reselers, :only => [:new, :show, :create]
    resources :product_lines, :only => [:show]
    resources :user_sessions, :only => [:new, :create, :destroy] 
    
    get "/" => "homes#index", :as => "root"
    post "/" => "homes#index", :as => "root"
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/synthetic_grass' => 'homes#synthetic_grass', via: :get
    match '/research_and_innovation' => 'homes#research_and_innovation', via: :get
    match '/warranty' => 'homes#warranty', via: :get
    match '/filters' => 'homes#filters', via: :post
    match '/filters' => 'homes#filters', via: :get

  end

end

#   end

app/models/product_line.rb
class ProductLine < ActiveRecord::Base
  #attr_accessible :name, :order, :active, :published
  has_attached_file :product_line_image, styles: { medium: "300x300>", thumb: "50x50>", otimize: "100%x100%"},processors: [:thumbnail, :compression]
  validates_attachment_content_type :product_line_image, :content_type => /\Aimage\/.*\Z/
  
  has_attached_file :product_line_internal_image, styles: { medium: "300x300>", thumb: "50x50>", otimize: "100%x100%"},processors: [:thumbnail, :compression]
  validates_attachment_content_type :product_line_internal_image, :content_type => /\Aimage\/.*\Z/
  
  has_attached_file :product_line_featured_image, styles: { medium: "300x300>", thumb: "50x50>", otimize: "100%x100%"},processors: [:thumbnail, :compression]
  validates_attachment_content_type :product_line_featured_image, :content_type => /\Aimage\/.*\Z/
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_many :products
end

app/controllers/admin/product_lines_controller.rb
class Admin::ProductLinesController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  def index
    @product_lines = ProductLine.all_active
  end

  def show
    @product_line = ProductLine.find_by_slug(params[:id])
  end

  def new
    @product_line = ProductLine.new
  end

  def create
    params.permit!
    @product_line = ProductLine.new(params[:product_line])
    if @product_line.save
      redirect_to admin_product_lines_url, :notice => "Successfully created product line."
    else
      render :action => 'new'
    end
  end

  def edit
    @product_line = ProductLine.find_by_slug(params[:id])
  end

  def update
    params.permit!
    @product_line = ProductLine.find_by_slug(params[:id])
    if @product_line.update_attributes(params[:product_line])
      redirect_to admin_product_lines_url, :notice  => "Successfully updated product line."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product_line = ProductLine.find_by_slug(params[:id])
    @product_line.newdestroy
    redirect_to admin_product_lines_url, :notice => "Successfully destroyed product line."
  end
end

app/controllers/product_lines_controller.rb
class ProductLinesController < ApplicationController
  before_filter :load_data
  def show
    @product_line = ProductLine.friendly.find(params[:id])
    @products = @product_line.products.all_published
  end
end

app/helpers/admin/product_lines_helper.rb
module Admin::ProductLinesHelper
end

app/helpers/product_lines_helper.rb
module ProductLinesHelper
end

app/views/admin/product_lines/_form.html.haml
= form_for [:admin, @product_line] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages

  .box-body        
    .form-group 
      = f.label :name
      = f.text_field :name, class: "form-control"
    .form-group 
      = f.label :order
      = f.text_field :order, class: "form-control"
    .form-group
      = f.label :product_line_image
      = f.file_field :product_line_image, :class => "form-control"
    - if @product_line.product_line_image.file?
      .form-group
        =image_tag(@product_line.product_line_image.url)
    .form-group
      = f.label :product_line_internal_image
      = f.file_field :product_line_internal_image, :class => "form-control"
    - if @product_line.product_line_internal_image.file?
      .form-group
        =image_tag(@product_line.product_line_internal_image.url)    
    .form-group
      = f.label :product_line_featured_image
      = f.file_field :product_line_featured_image, :class => "form-control"
    - if @product_line.product_line_featured_image.file?
      .form-group
        =image_tag(@product_line.product_line_featured_image.url)
        
        
    .form-group 
      = f.label :published
      = f.check_box :published
  .box-footer
    =f.submit nil, class: "btn btn-primary"

app/views/admin/product_lines/edit.html.haml
%section.content-header
  %h1
    ="Admin/Product Line"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active="Admin/Product Line"


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            ="Admin/Product Line"
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_product_lines_path, class:"btn btn-default"

app/views/admin/product_lines/index.html.haml
%section.content-header
  %h1
    =ProductLine.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=ProductLine.model_name.human()  
/ Main content
%section.content
  .col-xs-12
    %p= link_to "Nova #{ProductLine.model_name.human()} ", new_admin_product_line_path, class: "btn btn-primary"
    .box
      .box-header
        %h3.box-title="#{ProductLine.model_name.human(count: 2)}  Cadastrados"
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th=t("activerecord.attributes.product_line.product_line_image")
            %th=t("activerecord.attributes.product_line.name")
            %th=t("activerecord.attributes.product_line.order")
            %th=t("activerecord.attributes.product_line.published")
            %th=t("actions")
          - for product_line in @product_lines
            %tr
              %td= image_tag(product_line.product_line_image.url("thumb")) if product_line.product_line_image.file?
              %td= product_line.name
              %td= product_line.order
              %td= show_boolean(product_line.published)
              %td  
                = link_to t("edit"), edit_admin_product_line_path(product_line), class: "btn btn-default"
                = link_to t("destroy"),[:admin, product_line],  method: :delete , data:{confirm: t("msg_delete")}, class: "btn btn-default"
    %p= link_to "Nova #{ProductLine.model_name.human()} ", new_admin_product_line_path, class: "btn btn-primary"

app/views/admin/product_lines/new.html.haml
%section.content-header
  %h1
    ="Admin/Product Line"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active="Admin/Product Line"


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            ="Admin/Product Line"
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_product_lines_path, class: "btn btn-default"

app/views/admin/product_lines/show.html.haml
%section.content-header
  %h1
    =ProductLine.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active =ProductLine.model_name.human()  


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title= @product_line.name
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product_line.order")}:"
            %br
            = @product_line.order
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product_line.published")}:"
            %br
            = show_boolean(@product_line.published)
            
        
  = link_to t("back_list"), admin_product_lines_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_product_line_path(@product_line), class: "btn btn-default"
  = link_to "Nova #{ProductLine.model_name.human()}", new_admin_product_line_path, class: "btn btn-primary"