config/routes.rb
Rails.application.routes.draw do
  namespace(:admin){ resources :internal_images }
  namespace(:admin){ 
    resources :configuration_sites
    resources(:products) do
      resources :product_images
    end
    resources :fiber_types
    resources :roll_widths
    resources :height_fibreas
    resources :product_lines
    resources(:featureds) do
      member do 
        get :destroy_image
      end
    end 
    resources :newsletters
    resources :users
    root :to => 'products#index'
  }
  post '/tinymce_assets' => 'tinymce_assets#create'   
  post '/tinymce_documents' => 'tinymce_documents#create' 
  localized do
    resources :products, :only => [:show]
    resources :reselers, :only => [:new, :show, :create]
    resources :product_lines, :only => [:show]
    resources :user_sessions, :only => [:new, :create, :destroy] 
    
    get "/" => "homes#index", :as => "root"
    post "/" => "homes#index", :as => "root"
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/synthetic_grass' => 'homes#synthetic_grass', via: :get
    match '/research_and_innovation' => 'homes#research_and_innovation', via: :get
    match '/warranty' => 'homes#warranty', via: :get
    match '/filters' => 'homes#filters', via: :post
    match '/filters' => 'homes#filters', via: :get

  end

end

#   end

app/models/featured.rb
class Featured < ActiveRecord::Base
  #attr_accessible :active, :published
  has_attached_file :featured_image, styles: { medium: "300x300>", thumb: "50x50>", otimize: "100%x100%" },processors: [:thumbnail, :compression]
  validates_attachment_content_type :featured_image, :content_type => /\Aimage\/.*\Z/

  validates :featured_image, presence: true
end

app/controllers/admin/featureds_controller.rb
class Admin::FeaturedsController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  def index
    @featureds = Featured.all_active
  end

  def show
    @featured = Featured.find(params[:id])
  end

  def new
    @featured = Featured.new
  end

  def create
    params.permit!
    @featured = Featured.new(params[:featured])
    if @featured.save
      redirect_to [:admin, @featured], :notice => "Successfully created featured."
    else
      render :action => 'new'
    end
  end

  def edit
    @featured = Featured.find(params[:id])
  end

  def update
    params.permit!
    @featured = Featured.find(params[:id])
    if @featured.update_attributes(params[:featured])
      redirect_to [:admin, @featured], :notice  => "Successfully updated featured."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @featured = Featured.find(params[:id])
    @featured.newdestroy
    redirect_to admin_featureds_url, :notice => "Successfully destroyed featured."
  end
  
  def destroy_image
    params.permit!
    @featured = Featured.find(params[:id])
    @featured.featured_image = nil
    @featured.save
    render :action => 'edit'
  end
end

app/helpers/admin/featureds_helper.rb
module Admin::FeaturedsHelper
end

app/views/admin/featureds/_form.html.haml
= form_for [:admin, @featured] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages

  .box-body        
    .form-group 
      = f.label :title
      = f.text_field :title, class: "form-control", placeholder: t("activerecord.attributes.featured.title")
    .form-group
      = f.label :featured_image
      = f.file_field :featured_image, :class => "form-control"
    - if @featured.featured_image.file?
      .form-group
        =image_tag(@featured.featured_image.url, class: "img-responsive")
      /.form-group
      /  =link_to "Deletar Imagem", destroy_image_admin_featured_path(@featured.id), class: "btn btn-primary"
    .form-group 
      = f.label :link
      = f.text_field :link, class: "form-control", placeholder: t("activerecord.attributes.featured.link")
    .form-group 
      = f.label :published
      = f.check_box :published
  .box-footer
    =f.submit nil, :class => "btn btn-primary"

app/views/admin/featureds/edit.html.haml
%section.content-header
  %h1
    ="Admin/Featured"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active="Admin/Featured"


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            ="Admin/Featured"
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_featureds_path, :class => "btn btn-default"

app/views/admin/featureds/index.html.haml
%section.content-header
  %h1
    =Featured.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Featured.model_name.human()
/ Main content
%section.content
  .col-xs-12
    %p= link_to "Novo #{Featured.model_name.human()}", new_admin_featured_path, class: "btn btn-primary"
    .box
      .box-header
        %h3.box-title="#{Featured.model_name.human(count: 2)} Cadastrados"
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th=t("activerecord.attributes.featured.featured_image")
            %th=t("activerecord.attributes.featured.title")
            %th=t("activerecord.attributes.featured.published")
            %th=t("actions")
          - for featured in @featureds
            %tr
              %td= image_tag(featured.featured_image.url("thumb"))
              %td= featured.title
              %td= show_boolean(featured.published)
              %td  
                = link_to t("show"), [:admin, featured], :class => "btn btn-default"
                = link_to t("edit"), edit_admin_featured_path(featured), :class => "btn btn-default"
                = link_to t("destroy"), [:admin, featured], :confirm => t("msg_delete"), :method => :delete, :class => "btn btn-default"
    %p= link_to "Novo #{Featured.model_name.human()}", new_admin_featured_path, :class => "btn btn-primary"

app/views/admin/featureds/new.html.haml
%section.content-header
  %h1
    ="Admin/Featured"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active="Admin/Featured"


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            ="Admin/Featured"
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_featureds_path, :class => "btn btn-default"

app/views/admin/featureds/show.html.haml
%section.content-header
  %h1
    Admin/Featured  
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active Admin/Featured


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title=@featured.title
        .box-body 
          %p
            %b="#{t("activerecord.attributes.featured.featured_image")}:"
            %br
            =image_tag(@featured.featured_image.url, class: "img-responsive")
        .box-body  
          %p
            %b="#{t("activerecord.attributes.featured.published")}:"
            %br
            = show_boolean(@featured.published)
            
        
  = link_to t("back_list"), admin_featureds_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_featured_path(@featured), :class => "btn btn-default" 
  = link_to "Novo Admin/Featured", new_admin_featured_path, :class => "btn btn-primary"