config/routes.rb
Rails.application.routes.draw do
  namespace(:admin){ resources :internal_images }
  namespace(:admin){ 
    resources :configuration_sites
    resources(:products) do
      resources :product_images
    end
    resources :fiber_types
    resources :roll_widths
    resources :height_fibreas
    resources :product_lines
    resources(:featureds) do
      member do 
        get :destroy_image
      end
    end 
    resources :newsletters
    resources :users
    root :to => 'products#index'
  }
  post '/tinymce_assets' => 'tinymce_assets#create'   
  post '/tinymce_documents' => 'tinymce_documents#create' 
  localized do
    resources :products, :only => [:show]
    resources :reselers, :only => [:new, :show, :create]
    resources :product_lines, :only => [:show]
    resources :user_sessions, :only => [:new, :create, :destroy] 
    
    get "/" => "homes#index", :as => "root"
    post "/" => "homes#index", :as => "root"
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/synthetic_grass' => 'homes#synthetic_grass', via: :get
    match '/research_and_innovation' => 'homes#research_and_innovation', via: :get
    match '/warranty' => 'homes#warranty', via: :get
    match '/filters' => 'homes#filters', via: :post
    match '/filters' => 'homes#filters', via: :get

  end

end

#   end

app/models/product.rb
class Product < ActiveRecord::Base
  #attr_accessible :title, :description, :product_line_id, :height_fibrea_id, :roll_width_id, :fiber_type_id, :length_roll, :weight, :thickness_wire, :basis, :warranty

  has_attached_file :product_home_image, styles: { medium: "300x300>", thumb: "51x51#", home: "231x124#", internal: "680x464#"},processors: [:thumbnail, :compression]
  validates_attachment_content_type :product_home_image, :content_type => /\Aimage\/.*\Z/

  validates :product_line_id, presence: true 
  validates :height_fibrea_id, presence: true
  validates :roll_width_id, presence: true
  validates :fiber_type_id, presence: true
  validates :product_home_image, presence: true

  belongs_to :product_line
  belongs_to :height_fibrea
  belongs_to :roll_width
  belongs_to :fiber_type
  
  has_many :product_images
  
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  before_filter :load_categories, :only => [:new, :create, :edit, :update]
  def index
    @products = Product.all_active
  end

  def show
    @product = Product.find_by_slug(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    params.permit!
    @product = Product.new(params[:product])
    if @product.save
      redirect_to [:admin, @product], :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find_by_slug(params[:id])
  end

  def update
    params.permit!
    @product = Product.find_by_slug(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to [:admin, @product], :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find_by_slug(params[:id])
    @product.newdestroy
    redirect_to admin_products_url, :notice => "Successfully destroyed product."
  end
  
  def load_categories
    @product_lines = ProductLine.all_published.collect {|c| [c.name, c.id]}  
    @height_fibreas = HeightFibrea.all_published.collect {|c| [c.title, c.id]}  
    @roll_widths = RollWidth.all_published.collect {|c| [c.title, c.id]}
    @fiber_types = FiberType.all_published.collect {|c| [c.title, c.id]}
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :load_data
  def show
    @product = Product.where(slug: params[:id], active: true, published: true).first
    if @product.blank?
      redirect_to root_path
    else
      @product_images = @product.product_images.all_published
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
/-content_for :footer do
/  = tinymce_assets
/  = tinymce :basic
= form_for [:admin, @product] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages

  .box-body        
    .form-group 
      = f.label :title
      = f.text_field :title, class: "form-control"
    .form-group 
      = f.label :description
      = f.text_area :description, class: "form-control"
    .form-group 
      = f.label :product_line_id
      = f.select :product_line_id, @product_lines,{}, {class: "form-control"}
    .form-group 
      = f.label :height_fibrea_id
      = f.select :height_fibrea_id, @height_fibreas,{}, {class: "form-control"}
    .form-group 
      = f.label :roll_width_id
      = f.select :roll_width_id, @roll_widths,{}, {class: "form-control"}
    .form-group 
      = f.label :fiber_type_id
      = f.select :fiber_type_id, @fiber_types,{}, {class: "form-control"}
    .form-group 
      = f.label :length_roll
      = f.text_field :length_roll, class: "form-control"
    .form-group 
      = f.label :weight
      = f.text_field :weight, class: "form-control"
    .form-group 
      = f.label :thickness_wire
      = f.text_field :thickness_wire, class: "form-control"
    .form-group 
      = f.label :basis
      = f.text_field :basis, class: "form-control"
    .form-group 
      = f.label :warranty
      = f.text_field :warranty, class: "form-control"
    .form-group
      = f.label :product_home_image
      = f.file_field :product_home_image, :class => "form-control"
    - if @product.product_home_image.file?
      .form-group
        =image_tag(@product.product_home_image.url)
    .form-group 
      = f.label :published
      = f.check_box :published
  .box-footer
    =f.submit nil, class: "btn btn-primary"

app/views/admin/products/edit.html.haml
%section.content-header
  %h1
    =Product.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Product.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            =Product.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_products_path, class:"btn btn-default"

app/views/admin/products/index.html.haml
%section.content-header
  %h1
    =Product.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Product.model_name.human()  
/ Main content
%section.content
  .col-xs-12
    %p= link_to "Novo #{Product.model_name.human()} ", new_admin_product_path, class: "btn btn-primary"
    .box
      .box-header
        %h3.box-title="#{Product.model_name.human(count: 2)} Cadastrados"
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th=t("activerecord.attributes.product.product_home_image")
            %th=t("activerecord.attributes.product.title")
            %th=t("activerecord.attributes.product.published")
            %th=t("actions")
          - for product in @products
            %tr
              %td= image_tag(product.product_home_image.url("thumb"))
              %td= product.title
              %td= show_boolean(product.published)
              %td  
                = link_to t("show"), [:admin, product], class: "btn btn-default"
                = link_to t("edit"), edit_admin_product_path(product), class: "btn btn-default"
                = link_to t("destroy"),[:admin, product],  method: :delete , data:{confirm: t("msg_delete")}, class: "btn btn-default"
                = link_to "#{ProductImage.model_name.human(count: 2)}", admin_product_product_images_path(product), class: "btn btn-success"
    %p= link_to "Novo #{Product.model_name.human()} ", new_admin_product_path, class: "btn btn-primary"

app/views/admin/products/new.html.haml
%section.content-header
  %h1
    =Product.model_name.human() 
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Product.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            =Product.model_name.human() 
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_products_path, class: "btn btn-default"

app/views/admin/products/show.html.haml
%section.content-header
  %h1
    =Product.model_name.human()   
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active=Product.model_name.human() 


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title=Product.model_name.human() 
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.title")}:"
            %br
            = @product.title
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.description")}:"
            %br
            = @product.description
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.product_line_id")}:"
            %br
            = @product.product_line.name
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.height_fibrea_id")}:"
            %br
            = @product.height_fibrea.title
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.roll_width_id")}:"
            %br
            = @product.roll_width.title
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.fiber_type_id")}:"
            %br
            = @product.fiber_type.title
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.length_roll")}:"
            %br
            = @product.length_roll
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.weight")}:"
            %br
            = @product.weight
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.thickness_wire")}:"
            %br
            = @product.thickness_wire
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.basis")}:"
            %br
            = @product.basis
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.warranty")}:"
            %br
            = @product.warranty
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.product.published")}:"
            %br
            = show_boolean(@product.published)
        
  = link_to t("back_list"), admin_products_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_product_path(@product), class: "btn btn-default"
  = link_to "Novo #{Product.model_name.human()} ", new_admin_product_path, class: "btn btn-primary"
  = link_to "#{ProductImage.model_name.human(count: 2)}", admin_product_product_images_path(@product), class: "btn btn-success"