config/routes.rb
Rails.application.routes.draw do
  namespace(:admin){ resources :internal_images }
  namespace(:admin){ 
    resources :configuration_sites
    resources(:products) do
      resources :product_images
    end
    resources :fiber_types
    resources :roll_widths
    resources :height_fibreas
    resources :product_lines
    resources(:featureds) do
      member do 
        get :destroy_image
      end
    end 
    resources :newsletters
    resources :users
    root :to => 'products#index'
  }
  post '/tinymce_assets' => 'tinymce_assets#create'   
  post '/tinymce_documents' => 'tinymce_documents#create' 
  localized do
    resources :products, :only => [:show]
    resources :reselers, :only => [:new, :show, :create]
    resources :product_lines, :only => [:show]
    resources :user_sessions, :only => [:new, :create, :destroy] 
    
    get "/" => "homes#index", :as => "root"
    post "/" => "homes#index", :as => "root"
    match '/login' => 'user_sessions#new', via: :get  
    match '/logout' => 'user_sessions#destroy', via: :get
    match '/about' => 'homes#about', via: :get
    match '/synthetic_grass' => 'homes#synthetic_grass', via: :get
    match '/research_and_innovation' => 'homes#research_and_innovation', via: :get
    match '/warranty' => 'homes#warranty', via: :get
    match '/filters' => 'homes#filters', via: :post
    match '/filters' => 'homes#filters', via: :get

  end

end

#   end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base

end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < ApplicationController
  layout "admin"
  access_control do
      allow logged_in
  end
  def index
    @newsletters = Newsletter.all
  end

  def show
    @newsletter = Newsletter.find(params[:id])
  end

  def new
    @newsletter = Newsletter.new
  end

  def create
    params.permit!
    @newsletter = Newsletter.new(params[:newsletter])
    if @newsletter.save
      redirect_to [:admin, @newsletter], :notice => "Successfully created newsletter."
    else
      render :action => 'new'
    end
  end

  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  def update
    params.permit!
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.update_attributes(params[:newsletter])
      redirect_to [:admin, @newsletter], :notice  => "Successfully updated newsletter."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @newsletter = Newsletter.find(params[:id])
    #@newsletter.destroy
    redirect_to admin_newsletters_url, :notice => "Successfully destroyed newsletter."
  end
end

app/helpers/admin/newsletters_helper.rb
module Admin::NewslettersHelper
end

app/views/admin/newsletters/_form.html.haml
= form_for [:admin, @newsletter] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      = f.error_messages

  .box-body        
    .form-group 
      = f.label :email
      = f.text_field :email, :class => "form-control"
  .box-footer
    =f.submit nil, :class => "btn btn-primary"

app/views/admin/newsletters/edit.html.haml
%section.content-header
  %h1
    ="Admin/Newsletter"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active="Admin/Newsletter"


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title
            ="Admin/Newsletter"
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_newsletters_path, :class => "btn btn-default"

app/views/admin/newsletters/index.html.haml
%section.content-header
  %h1
    Admin/Newsletters  
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active Admin/Newsletters 
/ Main content
%section.content
  .col-xs-12
    %p= link_to "Novo Admin/Newsletter", new_admin_newsletter_path, :class => "btn btn-primary"
    .box
      .box-header
        %h3.box-title="Admin/Newsletters Cadastrados"
      .box-body.table-responsive.no-padding
        %table.table.table-hover
          %tr
            %th=t("activerecord.attributes.newsletter.email")
            %th=t("activerecord.attributes.newsletter.created_at")
            %th=t("actions")
          - for newsletter in @newsletters
            %tr
              %td= newsletter.email
              %td= I18n.l(newsletter.created_at, :format => :long)
              %td  
                = link_to t("destroy"),[:admin, newsletter],  method: :delete , data:{confirm: t("msg_delete")}, class: "btn btn-default"
    %p= link_to "Novo Admin/Newsletter", new_admin_newsletter_path, :class => "btn btn-primary"

app/views/admin/newsletters/new.html.haml
%section.content-header
  %h1
    ="Admin/Newsletter"
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active="Admin/Newsletter"


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title 
            ="Admin/Newsletter"
        / /.box-header
        / form start
        = render 'form'
      
        %p
          = link_to t("back_list"), admin_newsletters_path, :class => "btn btn-default"

app/views/admin/newsletters/show.html.haml
%section.content-header
  %h1
    Admin/Newsletter  
    %small Painel de Controle
  %ol.breadcrumb
    %li
      %a{:href => admin_root_path}
        %i.fa.fa-dashboard
        Home
    %li.active Admin/Newsletter


/ Main content
%section.content
  .row
    / left column
    .col-md-12
      / general form elements
      .box.box-primary
        .box-header
          %h3.box-title="Admin/Newsletter"
        .box-body  
          %p
            %b="#{t("activerecord.attributes.newsletter.email")}:"
            %br
            = @newsletter.email
            
        .box-body  
          %p
            %b="#{t("activerecord.attributes.newsletter.active")}:"
            %br
            = @newsletter.active
            
        
  = link_to t("back_list"), admin_newsletters_path, :class => "btn btn-default"
  = link_to t("edit"), edit_admin_newsletter_path(@newsletter), :class => "btn btn-default" 
  = link_to "Novo Admin/Newsletter", new_admin_newsletter_path, :class => "btn btn-primary"